BlogerBlogBundle_homepage:
    path:     /
    defaults: { _controller: "BlogerBlogBundle:Page:index" }
    requirements:
         methods:  GET

BlogerBlogBundle_about:
    path:   /about
    defaults: { _controller: "BlogerBlogBundle:Page:about" }
    requirements:
         methods:  GET

BlogerBlogBundle_contact:
      path:  /contact
      defaults: { _controller: "BlogerBlogBundle:Page:contact" }
      requirements:
      methods:  GET|POST

BlogerBlogBundle_blog_show:
    path:  /{id}/{slug}
    defaults: { _controller: "BlogerBlogBundle:Blog:show", comments: true }
    requirements:
        methods:  GET
        id: \d+

BlogerBlogBundle_comment_create:
    path:  /comment/{blog_id}
    defaults: { _controller: "BlogerBlogBundle:Comment:create" }
    requirements:
        methods:  POST
        blog_id: \d+